### ISSUE TITLE
dissconects while voice/cam

### ISSUE THREAD

**Issue by miztizm** [subrosa-io/subrosa-client#53]
Everytime i voice call or video call its discconects after like 1 minute or randomly on my srv
and when i recall this error appers on me or my buddy

``` javascript
Cannot set property 'state' of undefined
TypeError: Cannot set property 'state' of undefined
    at acceptCall (http://server.com/js/app-core.js:1047:25)
    at Array.<anonymous> (http://server.com/js/app-core.js:1037:17)
    at Object.api.emit (http://server.com/js/app-core.js:6:22)
    at HTMLDivElement.<anonymous> (http://server.com/js/app-view.js:758:7)
    at HTMLDivElement.jQuery.event.dispatch (http://server.com/vendor/jquery.js:4641:9)
    at HTMLDivElement.elemData.handle (http://server.com/vendor/jquery.js:4309:46)
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36

2app-webrtc.js:106 disconnected
app-core.js:1047 Uncaught TypeError: Cannot set property 'state' of undefined

```

The state that cannot be declared is INCALL
For the temp fix , i needed to change a heartbeat timing to true and comment a appcore.sock.close();
Now my friend connections least more than 2 hours.

**Comment by devcline** [comment]
For the temp fix , or i need to change a heartbeat timing to true and comment a appcore.sock.close();
Now my friend connections least more than 2 hours without hangouts
